[package]
name = "beasts_nft"
version = "0.1.0"
edition = "2024_07"

[lib]

[dependencies]
starknet = "2.10.1"
openzeppelin_access = "1.0.0"
openzeppelin_token = "1.0.0"
openzeppelin_introspection = "1.0.0"
openzeppelin_governance = "1.0.0"
openzeppelin_utils = "1.0.0"

[scripts]
test = "snforge test"

[dev-dependencies]
snforge_std = "0.46.0"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"

[profile.dev.cairo]


[features]
fuzzing = []

# Allow using the prebuilt snforge plugin and configure forks for testing
[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool.snforge]
exit_first = true

[[tool.snforge.fork]]
name = "sepolia"
url = "https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_8"
block_id.tag = "latest"
