[package]
cairo-version = "2.18.0"
name = "beasts_nft"
version = "0.1.0"
edition = "2024_07"

[lib]

[dependencies]
starknet = "2.18.0"
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_governance = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_utils = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }

[scripts]
test = "snforge test"

[dev-dependencies]
snforge_std = "0.60.0"

[[target.starknet-contract]]

[profile.dev.cairo]

# Allow using the prebuilt snforge plugin and configure forks for testing
[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[tool.snforge]
exit_first = true

[[tool.snforge.fork]]
name = "sepolia"
url = "https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_8"
block_id.tag = "latest"

[[tool.snforge.fork]]
name = "mainnet"
url = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_8"
block_id.tag = "latest"
